config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :room_messages
  resources :rooms

  resources :users, only: [:create, :new, :update, :edit, :show] do
    member do
      get :confirm_email
    end
  end

  # post '/alexa' do
  #   p request.body.read
  # end

  get 'auth/google_oauth2', to: 'auth#google_oauth'
  get 'auth/google_oauth2/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  match 'auth/facebook/callback', to: 'sessions#create', via: [:get, :post]

  resources :sessions, only: [:new, :create, :destroy]
  resources :recipes, only: [:index, :show]
  resources :ingredients, only: [:create, :new, :edit, :update, :destroy]
  resources :recipe_ingredients, only: [:destroy]
  resources :steps, only: [:create, :new, :edit, :update, :destroy]
  resources :favorites, only: [:index, :create, :destroy]
  resources :forbidden, only: [:show]

  resources :users do
    resources :recipes, only: [:create, :new, :edit, :update, :destroy]
    resources :crop_images, only: [:new, :create, :show, :edit]
    resources :friends, only: [:create, :update, :index, :destroy]
  end

  namespace :dashboard do
    get '/', to: 'dashboard#index'
    resources :my_recipes, only: [:index, :show]
    resources :my_profile, only: [:show, :edit]
  end

  resources :recipes do
    resources :comments, only: [:create, :new, :edit, :update, :destroy]
    resources :crop_recipe_images, only: [:new, :create]
  end

  resources :comments do
    resources :comments, only: [:create, :new, :edit, :update, :destroy]
  end

  namespace :api do
    namespace :v1 do
      resources :recipes, only: [:index, :show]
    end
  end


  # match "*path", to: "application#render_not_found", via: :all
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  attr_accessor :crop_x,
                :crop_y,
                :crop_w,
                :crop_h

  validates_presence_of :title
  validates_presence_of :description, presence: true, length: { minimum: 5 }
  validates_presence_of :recipe_type
  validates_presence_of :user_id
  validate :image_size

  has_many :recipe_ingredients, dependent: :destroy
  has_many :ingredients, through: :recipe_ingredients
  has_many :steps
  has_many :comments, as: :commentable
  has_one_attached :image

  def image_size
    if self.image.attached?
      image.blob.analyze
      errors.add :image, 'too big!' if image.blob.metadata[:width] > 4096
      errors.add :image, 'too small!' if image.blob.metadata[:width] < 200 || image.blob.metadata[:height] < 200
    end
  end

  def self.get_recipes(search_params)
    Recipe.where("title LIKE ?", "%#{search_params[:q].downcase.titleize}%").includes(:recipe_ingredients, :ingredients)
  end

  def self.my_recipes(id)
    Recipe.where(user_id: id)
  end

  def small_thumbnail
    return self.image.variant(resize: '150x150').processed
  end

  def cropped_image
    return self.image.variant(crop: self.image_coords ).processed
  end

  def thumbnail
    return self.image.variant(resize: '300x300').processed
  end

  def show_image
    return self.image.variant(resize: '500x500').processed
  end

  def get_recipe(id)
    Recipe.find(id)
  end
end

app/controllers/api/v1/recipes_controller.rb
class Api::V1::RecipesController < Api::V1::ApiBaseController

  def index
    render json: RecipeSerializer.new(Recipe.all)
  end

  def show
    render json: RecipeSerializer.new(Recipe.where("title LIKE ?", "%#{search_params[:id].downcase.titleize}%"))
  end

  private

  def search_params
    params.permit(:id)
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_user, only: [:show, :new, :create, :edit, :update, :destroy]

  def index
    @query = search_params[:q]
    @recipes = Recipe.get_recipes(search_params)
    @recipes_facade = RecipeFacade.new(@recipes)
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipes_facade = RecipeFacade.new(@recipes)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.update(title: recipe_params[:title].downcase.titleize)
    @recipe.update(user_id: @user.id)
    @recipe.update(recipe_type: params[:recipe_type])
    if @recipe.save
      redirect_to new_ingredient_path(@recipe.id)
    else
      flash[:error] = @recipe.errors.full_messages
      render :new
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    @ingredient = @recipe.ingredients.first
    if @ingredient.nil?
      redirect_to edit_ingredient_path(@recipe.id)
    elsif
      @recipe.update(recipe_params)
      redirect_to edit_ingredient_path(@ingredient.id, @recipe.id)
    else
      flash[:error] = @recipe.errors.full_messages
      redirect_to edit_user_recipe_path(@recipe.id)
    end
  end

  def destroy
    recipe = Recipe.find(params[:id])
    recipe_title = recipe.title
    if current_user && current_user.id == recipe.user_id
      Favorite.where(recipe_id: recipe.id).destroy_all
      Step.where(recipe_id: recipe.id).destroy_all
      recipe.destroy
      flash[:message] = "You have successfully deleted #{recipe_title}"
      redirect_to dashboard_my_recipes_path
    else
      flash[:error] = "You do not have permission to perform this action. Your id now has a strike and you have been reported for attempting to attack this site."
    end
  end

  private

  def set_user
    @user = current_user
  end

  def search_params
    params.permit(:q)
  end

  def recipe_params
    params.require(:recipe).permit(:title, :description, :recipe_type, :user_id, :image)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_recipe_form.html.erb
<section>
  <%= form_for [@user, @recipe] do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= label_tag :recipe_type, "Recipe Type" %>
    <%= select_tag :recipe_type, options_for_select(recipe_type), class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image, 'Add a Picture' %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
    <% if @recipe.title == nil %>
      <%= f.submit 'Create Recipe', class: "btn btn-primary" %>
    <% else %>
      <div class="detail-section">
        <div class="detail">
          <%= f.submit 'Update Recipe', class: "btn btn-primary" %>
        </div>
        <div class="detail">
          <%= link_to 'Cancel', dashboard_my_recipes_path, class: "btn btn-danger" %>
        </div>
      </div>

    <% end %>
  <% end %>
</section>

app/views/recipes/_recipe_show.html.erb
<div class="recipe-show">
  <div class="recipe-inline">
    <div class="description-show">
      <div class="recipe-title-show">
        <h1><%= @recipe.title %></h1>
        <div class="review-rating" data-score = "<%= @recipes_facade.get_rating(@recipe.id) %>"></div>
        <p>
          <%= @recipe.comments.count %> Reviews
        </p>
      </div>
      <div class="description">
        <%=  @recipe.description%>
        <br>
        <!-- <div class="portion">
          Choose Number of Portions: <input type="number" id="user-portion", min="1", max="25", step="1">
          <button id="submit-portion">Submit</button>
        </div> -->
        <br>
        <div class="recipe-description-show">
          <p id="ingredients">Ingredients:</p>
          <div class="ingredient"><% @recipe.ingredients.each do |ingredient| %>
            <% recipe_ingredient = @recipes_facade.get_recipe_ingredients(@recipe.id, ingredient.id) %>
              <% if recipe_ingredient.quantity > 1 %>
                <div class="name"><%= "#{recipe_ingredient.quantity} #{recipe_ingredient.measurement}s #{ingredient.name}" %></div>
                <% else %>
                <div class="name"><%= "#{recipe_ingredient.quantity} #{recipe_ingredient.measurement} #{ingredient.name}" %></div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="recipe-image">
      <img src=>
      <% if @recipe.image.attached? %>
      <%= image_tag(url_for(@recipe.show_image)) %>
      <% end %>
    </div>
  </div>
  <br>
  <div class="recipe-show-steps">
    <h3>Directions:</h3>
    <br>
    <% @recipe.steps.each_with_index do |step, i| %>
      <p>Step <%= i + 1 %>: </p>
      <div class="recipe-step">
        <%= step.step %>
      </div>
      <br>
    <% end %>
  </div>
</div>

app/views/recipes/edit.html.erb
<%= render '/dashboard/dashboard/dash_nav' %>
<br>
  <div class="new-recipe">
    <h4>Edit Recipe</h4>
    <%= render partial: "recipe_form"%>
  </div>
</div>

app/views/recipes/index.html.erb
<body>
  <header class="header">
      <div class="main-title">
        <h1 class="title">Recipes</h1>
      </div>
  </header>
  <div class="recipe-count">
    <% if @query == "" %>
      <p><%= @recipes.count %> results for "all recipes"</p>
    <% elsif @recipes.count == 1 %>
      <p><%= @recipes.count %> result for "<%= @query %>"</p>
    <% else %>
      <p><%= @recipes.count %> results for "<%= @query %>"</p>
    <% end %>
  </div>
  <main class="main">
    <div class="card-container">
      <% @recipes.each_with_index do |recipe, i| %>
        <div class="recipe">
          <a href="#">
            <div class="recipe-image">
              <img src=>
              <% recipe_image = recipe.get_recipe(recipe.id) %>
              <% if recipe_image.image.attached? %>
                <%= image_tag(url_for(recipe_image.cropped_image)) %>
              <% end %>
            </div>
            <div class="recipe-title">
              <h2><%= link_to recipe.title, recipe_path(recipe.id) %></h2>
            </div>
            <div class="review-rating" id="review-rating-index" data-score = "<%= @recipes_facade.get_rating(recipe.id) %>"></div>
            <div class="description">
              <p><%= link_to recipe.description, recipe_path(recipe.id) %></p>
            </div>
            <div>
              <div class="author">
                <% author = User.find(recipe.user_id) %>
                <p>
                  <%= link_to "By #{author.first_name.capitalize}  #{author.last_name.first.capitalize}.", user_path(author.id), :style=> 'font-family: "Apple Chancery", cursive;' %>
                </p>
                <div class="author-profile-picture">
                  <% if author.avatar.attached? %>
                  <%= image_tag(url_for(author.cropped_avatar), height: '40', :id => "my-profile-picture") %>
                  <% else %>
                  <%= image_tag("user_image.png", height: '40')%>
                  <% end %>
                </div>
              </div>
            </div>
            <div>
              <ul class="ingredients"><% recipe.ingredients.each do |ingredient| %>
                <% end %>
              </ul>
            </div>
            </a>
          </div>
        <% end %>
      </div>
  </main>
</body>

<!-- JS Script for Raty -->
<%= render '/comments/rating_script' %>

app/views/recipes/new.html.erb
<br>
  <div class="new-recipe">
    <h4>Create a Recipe</h4>
    <%= render partial: "recipe_form"%>
  </div>
</div>

app/views/recipes/show.html.erb
<div>
    <%= render partial: "recipe_show"%>
    <table class="favorites-button">
      <tr>
        <th>
          <% if current_user %>
            <% if @recipes_facade.recipe_favorited?(@recipe.id, @user.id).nil? %>
              <%= button_to 'Add to Favorites', favorites_path(@recipe), method: :post, class: "btn btn-primary"  %>
            <% else %>
              <%= button_to 'Remove from my Favorites', favorite_path(@recipe), method: :delete, class: "btn btn-danger"  %>
            <% end %>
          <% end %>
        </th>
      </tr>
    </table>
</div>
<% if current_user %>
<div class="comments">
  <h5>Reviews:</h5>
  <div class="comment-form">
    <%= render @recipe.comments %>
  </div>

    <%= form_for([@recipe, @recipe.comments.build]) do |f| %>
      <%= f.hidden_field :user_id, value: @user.id %>
      <%= f.hidden_field :recipe_id, value: @recipe.id %>

      <div id="rating-form">
        <label>Rating</label>
      </div>

      <%= f.text_area :content, placeholder: "Comment" %><br/>
      <%= f.submit "Add Comment"  %>
    <% end %>
<% end %>
</div>

<!-- JS script for Raty -->
<%= render '/comments/review_rating_script' %>