config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :room_messages
  resources :rooms

  resources :users, only: [:create, :new, :update, :edit, :show] do
    member do
      get :confirm_email
    end
  end

  # post '/alexa' do
  #   p request.body.read
  # end

  get 'auth/google_oauth2', to: 'auth#google_oauth'
  get 'auth/google_oauth2/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  match 'auth/facebook/callback', to: 'sessions#create', via: [:get, :post]

  resources :sessions, only: [:new, :create, :destroy]
  resources :recipes, only: [:index, :show]
  resources :ingredients, only: [:create, :new, :edit, :update, :destroy]
  resources :recipe_ingredients, only: [:destroy]
  resources :steps, only: [:create, :new, :edit, :update, :destroy]
  resources :favorites, only: [:index, :create, :destroy]
  resources :forbidden, only: [:show]

  resources :users do
    resources :recipes, only: [:create, :new, :edit, :update, :destroy]
    resources :crop_images, only: [:new, :create, :show, :edit]
    resources :friends, only: [:create, :update, :index, :destroy]
  end

  namespace :dashboard do
    get '/', to: 'dashboard#index'
    resources :my_recipes, only: [:index, :show]
    resources :my_profile, only: [:show, :edit]
  end

  resources :recipes do
    resources :comments, only: [:create, :new, :edit, :update, :destroy]
    resources :crop_recipe_images, only: [:new, :create]
  end

  resources :comments do
    resources :comments, only: [:create, :new, :edit, :update, :destroy]
  end

  namespace :api do
    namespace :v1 do
      resources :recipes, only: [:index, :show]
    end
  end


  # match "*path", to: "application#render_not_found", via: :all
end

app/controllers/dashboard/base_controller.rb
class Dashboard::BaseController < ApplicationController
  before_action :require_registered_user
end

app/controllers/dashboard/dashboard_controller.rb
class Dashboard::DashboardController < Dashboard::BaseController
  def index
      @favorites_facade = FavoriteFacade.new(@user)
  end
end

app/controllers/dashboard/my_profile_controller.rb
class Dashboard::MyProfileController < Dashboard::BaseController
  before_action :authenticate_user

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  private

  def authenticate_user
    if current_user.id != params[:id].to_i
      flash[:danger] = "Warning! Attempted Breach!"
      redirect_to forbidden_path(params[:id])
    end
  end
end

app/controllers/dashboard/my_recipes_controller.rb
class Dashboard::MyRecipesController < Dashboard::BaseController
  def index
    @my_recipes = Recipe.my_recipes(@user.id)
    @recipes_facade = RecipeFacade.new(@recipes)
  end

  def show
    @user = current_user
    @recipe = Recipe.find(params[:id])
    @recipes_facade = RecipeFacade.new(@recipes)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @user = current_user
    if current_user.nil?
      flash[:message] = 'You must log in or register to become a member'
      redirect_to new_session_path
    end
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/my_recipes/index.html.erb
<%= render '/dashboard/dashboard/dash_nav' %>

<body>
  <header class="header">
      <div class="main-title">
        <h1 class="title">My Recipes</h1>
      </div>
  </header>
  <div class="recipe-count">
    <% if @my_recipes.count == 1 %>
      <p><%= @my_recipes.count %> recipe</p>
    <% else %>
      <p><%= @my_recipes.count %> recipes</p>
    <% end %>
  </div>
  <main class="main">
    <div class="card-container">
      <% @my_recipes.each_with_index do |recipe, i| %>
        <div class="recipe">
          <a href="#">
            <div class="recipe-image">
              <img src=>
              <% recipe_image = recipe.get_recipe(recipe.id) %>
              <% if recipe_image.image.attached? %>
                <%= image_tag(url_for(recipe_image.cropped_image)) %>
              <% end %>
            </div>
            <div class="review-rating" id="review-rating-index" data-score = "<%= @recipes_facade.get_rating(recipe.id) %>"></div>
            <div class="recipe-title">
              <h2><%= link_to recipe.title, dashboard_my_recipe_path(recipe.id) %></h2>
            </div>
            <div class="description">
              <p><%= link_to recipe.description, dashboard_my_recipe_path(recipe.id) %></p>
              </div>
            </a>
          </div>
        <% end %>
      </div>
  </main>
</body>

<!-- JS Script for Raty -->
<%= render '/comments/rating_script' %>

app/views/dashboard/my_recipes/show.html.erb
<br>
<div class="edit-recipe">
    <%= render '/recipes/recipe_show' %>
    <table class="edit-delete-recipe-buttons">
      <tr>
        <th>
          <%= button_to 'Edit Recipe', edit_user_recipe_path(@recipe.id), method: :get, class: "btn btn-primary" %>
        </th>
        <th class="delete-recipe">
          <%= button_to 'Delete Recipe', user_recipe_path(@recipe.id), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
        </th>
        <th>
          <% if current_user %>
            <% if @recipes_facade.recipe_favorited?(@recipe.id, @user.id).nil? %>
              <%= button_to 'Add to Favorites', favorites_path(@recipe), method: :post, class: "btn btn-primary"  %>
            <% else %>
              <%= button_to 'Remove from my Favorites', favorite_path(@recipe), method: :delete, class: "btn btn-danger"  %>
            <% end %>
          <% end %>
        </th>
      </tr>
    </table>
</div>
<br>

<!-- JS Script for Raty -->
<%= render '/comments/rating_script' %>