config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :room_messages
  resources :rooms

  resources :users, only: [:create, :new, :update, :edit, :show] do
    member do
      get :confirm_email
    end
  end

  # post '/alexa' do
  #   p request.body.read
  # end

  get 'auth/google_oauth2', to: 'auth#google_oauth'
  get 'auth/google_oauth2/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  match 'auth/facebook/callback', to: 'sessions#create', via: [:get, :post]

  resources :sessions, only: [:new, :create, :destroy]
  resources :recipes, only: [:index, :show]
  resources :ingredients, only: [:create, :new, :edit, :update, :destroy]
  resources :recipe_ingredients, only: [:destroy]
  resources :steps, only: [:create, :new, :edit, :update, :destroy]
  resources :favorites, only: [:index, :create, :destroy]
  resources :forbidden, only: [:show]

  resources :users do
    resources :recipes, only: [:create, :new, :edit, :update, :destroy]
    resources :crop_images, only: [:new, :create, :show, :edit]
    resources :friends, only: [:create, :update, :index, :destroy]
  end

  namespace :dashboard do
    get '/', to: 'dashboard#index'
    resources :my_recipes, only: [:index, :show]
    resources :my_profile, only: [:show, :edit]
  end

  resources :recipes do
    resources :comments, only: [:create, :new, :edit, :update, :destroy]
    resources :crop_recipe_images, only: [:new, :create]
  end

  resources :comments do
    resources :comments, only: [:create, :new, :edit, :update, :destroy]
  end

  namespace :api do
    namespace :v1 do
      resources :recipes, only: [:index, :show]
    end
  end


  # match "*path", to: "application#render_not_found", via: :all
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  enum ingredient_type: [ :herb, :fruit, :liquid, :protein, :spice, :vegetable ]

  validates_presence_of :name
  validates_presence_of :ingredient_type

  has_many :recipe_ingredients, dependent: :destroy
  has_many :recipes, through: :recipe_ingredients
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def new
    @recipe = Recipe.find(params[:format])
    @ingredient = Ingredient.new
    @recipes_facade = RecipeFacade.new(@recipe)
  end

  def create
    if params[:format].nil?
      @recipe = Recipe.find(params[:ingredient][:recipe_id])
    else
      @recipe = Recipe.find(params[:format])
    end
    @ingredient = Ingredient.find_or_create_by(ingredient_params)
    if @ingredient.save
      @ingredient.update(ingredient_type: params[:ingredient_type])
      create_recipe_ingredient(@recipe, @ingredient)
    else
      flash[:error] = @ingredient.errors.full_messages
      render :new
    end
  end

  def edit
    @user = current_user
    @recipes_facade = RecipeFacade.new(@recipe)
    if params[:format].nil?
      @recipe = Recipe.find(params[:id])
      @ingredient = Ingredient.new
    else
      @ingredient = Ingredient.find(params[:id])
      @recipe = Recipe.find(params[:format])
    end
  end

  def update
    @recipe = Recipe.find(params[:ingredient][:recipe_id])
    @ingredient = Ingredient.find(params[:id])
    if @ingredient.update(ingredient_params)
      @ingredient.update(ingredient_type: params[:ingredient_type])
      update_recipe_ingredient(@recipe, @ingredient)
    else
      flash[:error] = @ingredient.errors.full_messages
      redirect_to edit_ingredient_path(@ingredient.id, @recipe.id)
    end
  end

  private

  def ingredient_params
    ingredients = {
      name: params[:ingredient][:name],
      ingredient_type: params[:ingredient_type]
    }
  end

  def create_recipe_ingredient(recipe, ingredient)
    @recipe_ingredient = RecipeIngredient.new(recipe_ingredients_params(recipe, ingredient))
    if @recipe_ingredient.save
      flash[:message] = "Your ingredient has been added to #{@recipe.title}"
      redirect_to new_ingredient_path(@recipe.id)
    else
      flash[:error] = @recipe_ingredient.errors.full_messages
      render :new
    end
  end

  def recipe_ingredients_params(recipe, ingredient)
    ri_params = {
      measurement_type: params[:measurement_type],
      measurement: params[:measurement],
      quantity: params[:ingredient][:recipe_ingredients][:quantity],
      ingredient_id: ingredient.id,
      recipe_id: recipe.id
    }
  end

  def update_recipe_ingredient(recipe, ingredient)
    @recipe_ingredient = RecipeIngredient.where(recipe_id: recipe.id).find_by(ingredient_id: ingredient.id)
    @recipe_ingredient.update(
      measurement_type: params[:measurement_type],
      measurement: params[:measurement],
      quantity: params[:ingredient][:recipe_ingredient][:quantity],
      ingredient_id: ingredient.id,
      recipe_id: recipe.id
    )
    if @recipe_ingredient.save
      flash[:message] = "#{ingredient.name.titleize} has been updated for #{@recipe.title}"
      redirect_to edit_ingredient_path(ingredient.id, recipe.id)
    else
      flash[:error] = @recipe_ingredient.errors.full_messages
      render :new
    end
  end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_ingredient_form.html.erb
<br>
  <h3> <%= @recipe.title %> </h3>
  <p>Ingredients: </p>
  <% @recipe.ingredients.each_with_index do |ingredient, i| %>
    <div class="ingredient-<%= i + 1 %>">
      <div class="detail-section">
        <div class="detail">
          <h5 class="ingredient-name"><%= ingredient.name %></h5>
          <% recipe_ingredient = @recipes_facade.get_recipe_ingredients(@recipe.id, ingredient.id) %>
            <% if recipe_ingredient.quantity > 1 %>
              <div class="name"><%= "#{recipe_ingredient.quantity} #{recipe_ingredient.measurement}s #{ingredient.name}" %></div>
              <% else %>
              <div class="name"><%= "#{recipe_ingredient.quantity} #{recipe_ingredient.measurement} #{ingredient.name}" %></div>
            <% end %>
        </div>
        <div class="detail">
          <%= link_to 'Edit', edit_ingredient_path(ingredient.id, @recipe.id), class: "btn btn-secondary"   %>
        </div>
        <div class="detail">
          <%= button_to 'Delete', recipe_ingredient_path(recipe_ingredient.id, @recipe.id), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
        </div>
      </div>
    </div>
  <% end %>
  <div class="detail">
    <%= button_to 'Add Ingredient', new_ingredient_path(@recipe.id), method: :get, class: "btn btn-secondary" %>
  </div>
  <br>
  <h5>Update: <%= @ingredient.name %></h5>
  <section>
    <%= form_for @ingredient do |f| %>
    <div>
      <div>
        <%= f.hidden_field :recipe_id, value: @recipe.id %>
      </div>
      <div>
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div>
        <%= label_tag :recipe_type, "Ingredient Type" %>
        <%= select_tag :ingredient_type, options_for_select(ingredient_type), class: "form-control" %>
      </div>
      <% recipe_ingredients = @recipes_facade.get_recipe_ingredients(@recipe.id, @ingredient.id) %>
      <% if recipe_ingredients.nil? %>
      <%= f.fields_for :recipe_ingredients do |recipe_ingredient| %>
        <div>
          <%= label_tag :recipe_type, "Measurement Type" %>
          <%= select_tag :measurement_type, options_for_select(measurement_type), class: "form-control" %>
        </div>
        <div>
          <%= label_tag :recipe_type, "Measurement" %>
          <%= select_tag :measurement, grouped_options_for_select(measurement), class: "form-control" %>
        </div>
        <div>
          <%= recipe_ingredient.label :quantity %>
          <%= recipe_ingredient.number_field :quantity, step: 0.25, class: "form-control" %>
        </div>
      <% end %>
      <div class="submit-ingredient">
        <%= f.submit 'Add Ingredient', class: "btn btn-primary" %>
      </div>
      <% else %>
      <%= f.fields_for recipe_ingredients do |recipe_ingredient| %>
      <div>
        <%= label_tag :recipe_type, "Measurement Type" %>
        <%= select_tag :measurement_type, options_for_select(measurement_type), class: "form-control" %>
      </div>
      <div>
        <%= label_tag :recipe_type, "Measurement" %>
        <%= select_tag :measurement, grouped_options_for_select(measurement), class: "form-control" %>
      </div>
      <div>
        <%= recipe_ingredient.label :quantity %>
        <%= recipe_ingredient.number_field :quantity, step: 0.25, class: "form-control" %>
      </div>
      <% end %>
      <div class="detail-section">
        <div class="detail">
          <%= f.submit 'Update Ingredient', class: "btn btn-primary" %>
      <% end %>
    <% end %>
        </div>
        <div class="detail">
          <%= button_to 'Next', edit_step_path(@recipe.id), method: :get, class: "btn btn-success" %>
        </div>
      </div>
  </section>
</div>

app/views/ingredients/_recipe_ingredient.html.erb
<%= f.fields_for :recipe_ingredients do |recipe_ingredient| %>
  <div>
    <%= label_tag :recipe_type, "Measurement Type" %>
    <%= select_tag :measurement_type, options_for_select(measurement_type), class: "form-control" %>
  </div>
  <div>
    <%= label_tag :recipe_type, "Measurement" %>
    <%= select_tag :measurement, options_for_select(measurement), class: "form-control" %>
  </div>
  <div>
    <%= recipe_ingredient.label :quantity %>
    <%= recipe_ingredient.number_field :quantity, step: 0.25, class: "form-control" %>
  </div>
<% end %>
<div class="submit-ingredient">
  <%= f.submit 'Add Ingredient', class: "btn btn-primary" %>
</div>

app/views/ingredients/edit.html.erb
<%= render '/dashboard/dashboard/dash_nav' %>
<br>
  <div class="new-recipe">
    <h4>Edit Ingredient</h4>
    <%= render partial: "ingredient_form"%>
  </div>
</div>

app/views/ingredients/new.html.erb
<br>
  <div class="new-recipe">
    <h3> <%= @recipe.title %> </h3>
    <p>Ingredients: </p>
    <% @recipe.ingredients.each do |ingredient| %>
    <div class="detail-section">
      <div class="detail">
        <h5 class="ingredient-name"><%= ingredient.name %></h5>
        <% recipe_ingredient = @recipes_facade.get_recipe_ingredients(@recipe.id, ingredient.id) %>
          <% if recipe_ingredient.quantity > 1 %>
            <div class="name"><%= "#{recipe_ingredient.quantity} #{recipe_ingredient.measurement}s #{ingredient.name}" %></div>
            <% else %>
            <div class="name"><%= "#{recipe_ingredient.quantity} #{recipe_ingredient.measurement} #{ingredient.name}" %></div>
          <% end %>
      </div>
      <div class="detail">
        <%= link_to 'Edit', edit_ingredient_path(ingredient.id, @recipe.id), class: "btn btn-secondary"   %>
      </div>
      <div class="detail">
        <%= button_to 'Delete', recipe_ingredient_path(recipe_ingredient.id, @recipe.id), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
      </div>
    </div>
    <% end %>
    <br>
    <h5>Add Ingredients</h5>
    <section id="recipe-ingredient-id">
      <%= form_for @ingredient do |f| %>
      <div>
        <div>
          <%= f.hidden_field :recipe_id, value: @recipe.id %>
        </div>
        <div>
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div>
          <%= label_tag :recipe_type, "Ingredient Type" %>
          <%= select_tag :ingredient_type, options_for_select(ingredient_type), class: "form-control" %>
        </div>
        <%= f.fields_for :recipe_ingredients do |recipe_ingredient| %>
          <div>
            <%= label_tag :recipe_type, "Measurement Type" %>
            <%= select_tag :measurement_type, options_for_select(measurement_type), class: "form-control" %>
          </div>
          <div>
            <%= label_tag :recipe_type, "Measurement" %>
            <%= select_tag :measurement, grouped_options_for_select(measurement), class: "form-control" %>
          </div>
          <div>
            <%= recipe_ingredient.label :quantity %>
            <%= recipe_ingredient.number_field :quantity, step: 0.25, class: "form-control" %>
          </div>
        <% end %>
        <div class="detail-section">
          <div class="detail">
            <%= f.submit 'Add Ingredient', class: "btn btn-primary" %>
          </div>
      <% end %>
          <div class="detail">
            <%= button_to 'Next', new_step_path(@recipe.id), method: :get, class: "btn btn-success" %>
          </div>
        </div>
      </div>
    </section>
  </div>
</div>